### ISSUE TITLE
280 MB of dependencies for this?

### ISSUE THREAD

**Issue by jtmueller** [aws-geospatial/amazon-location-utilities-auth-helper-js#29]
### Describe the bug

Create an empty node project. Install this npm package. Several minutes later your node_modules folder takes up 200+ MB.

Is that really necessary? Why does a JavaScript auth helper pull in _all of React Native_ (59.6 MB)? I'm not using any flavor of React.

Also there's warnings about 9 deprecated packages this library depends on.

Please clean up your dependencies!

### Expected Behavior

This dependency should not increase the size of my docker image by 40% for the sake of `withAPIKey(...).getLocationClientConfig()`.

### Current Behavior

My node_modules folder went from 100 MB to 300 MB just from this one package!

### Reproduction Steps

Create an empy node project. Install this npm package. Several minutes later your node_modules folder takes up 200+ MB.

### Environment details (OS name and version, browser, etc.)

Irrelevant

**Comment by vinguthh** [comment]
Hi @jtmueller, thank you for bringing up the concern. We are currently working diligently to pinpoint the root cause and implement a solution for it.

**Comment by jtmueller** [comment]
@vinguthh thanks. I might be able to save you some time, the root cause is the `@aws-amplify/core` package, which is "a JavaScript library for frontend and mobile developers building cloud-enabled applications."

I'm attempting to build a back-end, Node application. I do not require 200MB of front-end dependencies, and my Docker image would be significantly smaller without all that stuff. I would greatly appreciate a version of this library without front-end depdendencies, or a suggestion as to what I can replace amazon-location-utilities-auth-helper with for back-end, Node.js code.

Thanks!

**Comment by raisen** [comment]
I'm also facing the same issue and was preventing my deployment to Lambda.

**Comment by cgalvan** [comment]
I repro'd this from an empty repo:

```
npm init
npm install npm install @aws/amazon-location-utilities-auth-helper
cd node_modules
du -h
```

This output from this is 280MB, I'll take a look at this.

**Comment by cgalvan** [comment]
I did a quick test by updating to the latest versions of our dependencies:

```
"dependencies": {
    "@aws-amplify/core": "^6.0.27",
    "@aws-sdk/client-location": "^3.549.0",
    "@aws-sdk/credential-providers": "^3.549.0",
    "@aws-sdk/types": "^3.535.0"
  },
```
This results in a `node_modules` folder of 37mb, which is much better :) So it seems the packages have trimmed their dependencies upstream.

There appear to be some breaking API changes with this update, so I'm looking into them now.

**Comment by cgalvan** [comment]
The updating of `@aws-sdk/client-location`, `@aws-sdk/credential-providers`, and `@aws-sdk/types` packages was straightforward, but when updating to the latest version of `@aws-amplify/core` it was discovered that the latest versions no longer export the `Signer` class we are using for generating a sigv4 signed URL in cognito mode.

Unfortunately, if I go back to a version of the package that still exports the `Signer` class, its dependencies hadn't been trimmed at that point so it still pulls in ~120MB.

I'm investigating some potential solutions to replace the `Signer` usage.

**Comment by cgalvan** [comment]
I've posted a PR https://github.com/aws-geospatial/amazon-location-utilities-auth-helper-js/pull/35 that reduces our dependencies to 19MB.

**Comment by cgalvan** [comment]
I've merged the PR, will publish a new release on Monday.

**Comment by cgalvan** [comment]
@jtmueller @raisen A new version `1.0.6` has been published that has this fix:

https://www.npmjs.com/package/@aws/amazon-location-utilities-auth-helper/v/1.0.6
